### ISSUE TITLE
Sandbox Data

### ISSUE THREAD

**Issue by MonDeveloper** [mastreeno/Merp#1]
This implementation of Event Sourcing is the perfect stuff to explain the theory behind DDD and ES to people with a pragmatic mindset. 
Anyway it misses something, the best partner in crime of this codebase is a set of data we could use to fulfill the system in order to play the time travel over the business data and show all the power to the skeptics.
Could you provide a bunch of demo data and a raw console to fill them into?

**Comment by andysal** [comment]
Hi,
I do agree that some sample data would provide an easy way to enjoy time travelling: currently, to test the project we are using a database created importing our accountancy db so we cannot share it.
I'll ask our legal department whether an anonymized version of such database could be made available for download
