### ISSUE TITLE
How to run the application?

### ISSUE THREAD

**Issue by bhaidar** [mastreeno/Merp#12]
Hello,
I've cloned the solution and open it in VS 2017. When I build the solution, I get the following errors:

![image](https://user-images.githubusercontent.com/1163421/44289883-d4870e80-a27e-11e8-9e54-e65ac56de0fa.png)

I made sure to restore client libraries and NUGET packages.

Any idea what to do here?

Thanks

**Comment by andysal** [comment]
As previously told, we're switching from AngularJS to VueJS so you need to install its tool chain (e.g.: NodeJS). The current codebase, though, is still largely reliant on AngularJS so to have the solution working you could just delete the src/Merp.Web.Site/wwwroot/lib/vue/ folder
