### ISSUE TITLE
Error handling in denormalizers

### ISSUE THREAD

**Issue by Liero** [mastreeno/Merp#13]
Hi,

I recently learned about rebus, that when one of the handlers (denormalizers) fails, the rest of them is not called. Additionally, retry strategy retries all handlers, not just the failed one. The explanation is:

> there's no way to partially consume a message and thus be able to retry delivery to the failing handler, message delivery is implemented as an "all-or-nothing"-operation.
This also means that a failure in one handler means that the rest of the handler pipeline will not be invoked.
https://github.com/rebus-org/Rebus/issues/745

To me this makes Rebus unsuitable messaging platform for denormalizers, because there is very high chance of getting into inconsistent state. One way to workaround it would be to use single UoW per all denormalizers and commit it in one transaction after all denormalizers succeeds.

The other issue I have is that EventStore implementation relies on dispatching events, but saving and dispatching event is not atomic operation. It can easily happen, that some events will not be dispatched (e.g. because of network for example) or that they will not be dispatched in the same order as they were saved.

**Comment by andysal** [comment]
Hi, we're about to shop MementoFX v2 and then start working on v3, which will include a feature (i.e. commit-based event storing) to address this scenario.

**Comment by Liero** [comment]
What you mean by commit based event storing?
