### ISSUE TITLE
How to generate the database?

### ISSUE THREAD

**Issue by fangyong988** [mastreeno/Merp#17]
How to generate the database?
help！ TKS

**Comment by andysal** [comment]
firstly, just create 3 empty databases named:
- Merp-Accountancy-Rebus
- Merp-Registry-Rebus
- Merp-TimeTracking-Rebus

then run the following Entity Framework Core migrations defined within the project named Merp.Web.Auth (these migrations create the tables needed by both ASP.NET Core's Identity and IdentityServer to persist clients, API resources and configuration data.):
- EntityFrameworkCore\Update-Database -Context PersistedGrantDbContext
- EntityFrameworkCore\Update-Database -Context ConfigurationDbContext
- EntityFrameworkCore\Update-Database -Context ApplicationDbContext

finally, run the migrations defined within each ".ReadModel" project, that is:
- Update-Database on Merp.Accountancy.QueryStack
- Update-Database on Merp.Accountancy.Drafts
- Update-Database on Merp.Registry.QueryStack
- Update-Database on Merp.TimeTracking.QueryStack
