### ISSUE TITLE
Who use 'Web.Api.Public' ?

### ISSUE THREAD

**Issue by taiti777** [mastreeno/Merp#18]
Hi, @andysal.
I read naa4e. That's exactly what I wanted. thanks!

By the way,
Who use _Controllers.InvoiceController.MarkInComingInvoiceAsPaid()_ ?
This recives arguments that model has _IncomingInvoice.Id_ .
But _IncomingInvoice.Id_ is inaccessible from outside of _IncomingInvoice instance_.

**Comment by andysal** [comment]
"Web.Api.Public" projects are intended to be used by agents external to the application, such as import tools or other applications (e.g.: integration purposes). Alas, at the very moment these APIs are a bit underdeveloped (and not on par with Merp's feature set) but we're working on them

**Comment by taiti777** [comment]
I see.
If such as integration event is implemented ,It will be more fun👍
