### ISSUE TITLE
codeplex moving

### ISSUE THREAD

**Issue by abdurahmanus** [mastreeno/Merp#3]
Hello, Andrea! Are you planning to move and upgrade cqrs and domain model examples from https://naa4e.codeplex.com/ ?

**Comment by andysal** [comment]
Hi! This Github repo already contains an updated version of Merp which runs on top of .NET Standard 2 (both .NET Framework and .NET Core then) whereas IBuyStuff has been discontinued since, due to time constraints (I do develop these samples in my spare time), I opted to focus on a single project.
